In [1]:
import pandas
import numpy as np
data = {
    '사원번호' : ['001', '002', '003', '004', '005', '006', '007', '008'],
    '부서명' : ['영업부', '인사부', '개발부', '개발부','인사부', '개발부','영업부', '개발부'],
    '사원명' : ['김자바', '이자바', '박자바', '정자바', '최자바', '강자바', '윤자바', '조자바'], # (단위 : 만 명)
    '근속년수':[3, 5, 1, 2, 3, 8, 6, 1],
    '사용언어':[np.nan, np.nan, 'Java', 'Python', np.nan, 'Python', np.nan, 'C#' ],
    '키' : [176.5, 161.1, 158.9, 177.5, 182.6, 166.6, 170.8, 174.7],
}
#DataFrame 객체 생성
df = pandas.DataFrame(data)
#사원번호 컬럼을 index로 지정
df.set_index('사원번호', inplace=True)
df

      부서명  사원명  근속년수    사용언어      키
사원번호
001   영업부  김자바     3     NaN  176.5
002   인사부  이자바     5     NaN  161.1
003   개발부  박자바     1    Java  158.9
004   개발부  정자바     2  Python  177.5
005   인사부  최자바     3     NaN  182.6
006   개발부  강자바     8  Python  166.6
007   영업부  윤자바     6     NaN  170.8
008   개발부  조자바     1      C#  174.7

1. 전체 데이터 중 '사원명' 정보만 출력하시오

In [3]:
df['사원명']

사원번호
001    김자바
002    이자바
003    박자바
004    정자바
005    최자바
006    강자바
007    윤자바
008    조자바
Name: 사원명, dtype: str

2. 전체 데이터 중에서 '부서명','사원명','근속년수' 정보를 출력하시오

In [4]:
df[['부서명', '사원명', '근속년수']]

      부서명  사원명  근속년수
사원번호
001   영업부  김자바     3
002   인사부  이자바     5
003   개발부  박자바     1
004   개발부  정자바     2
005   인사부  최자바     3
006   개발부  강자바     8
007   영업부  윤자바     6
008   개발부  조자바     1

3. 개발부서에 속한 사원들의 '부서명','사원명' 정보를 출력하시오

In [6]:
df[df['부서명'] == '개발부'][['부서명', '사원명']]

      부서명  사원명
사원번호
003   개발부  박자바
004   개발부  정자바
006   개발부  강자바
008   개발부  조자바

4. 키가 170.0 이하이거나 180.0 이상인 사원들의 '부서명', '사원명', '키'를 출력하시오

In [7]:
df[(df['키'] <= 170.0) | (df['키'] >= 180.0)][['부서명', '사원명', '키']]

      부서명  사원명      키
사원번호
002   인사부  이자바  161.1
003   개발부  박자바  158.9
005   인사부  최자바  182.6
006   개발부  강자바  166.6

5. 사용언어가 'NaN'인 데이터를 모두 '사용언어없음'으로 바꾸고, 바뀐 내용을 저장하여 출력하시오

In [9]:
df['사용언어'] = df['사용언어'].fillna('사용언어 없음')
df

      부서명  사원명  근속년수     사용언어      키
사원번호
001   영업부  김자바     3  사용언어 없음  176.5
002   인사부  이자바     5  사용언어 없음  161.1
003   개발부  박자바     1     Java  158.9
004   개발부  정자바     2   Python  177.5
005   인사부  최자바     3  사용언어 없음  182.6
006   개발부  강자바     8   Python  166.6
007   영업부  윤자바     6  사용언어 없음  170.8
008   개발부  조자바     1       C#  174.7