In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('test2.xlsx')
df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반    90    70  80   독서
1  이자바  자바반    80    80  80  NaN
2  박자바  자바반    70    80  75  NaN
3  최캐드  캐드반   100    70  85   요가
4  정캐드  캐드반    90    90  90   축구

In [ ]:
# ─────────────────────────────────────────────
# 결측치(Missing Value) 개념
# ─────────────────────────────────────────────
# 결측치 : 데이터 세트에서 누락된 값 (비어있는 데이터, NaN 데이터)
# NaN (Not a Number) : pandas에서 결측치를 표현하는 방식
#
# 결측치 처리 방법 2가지:
# 1) 결측치 제거  → dropna() 함수 사용
# 2) 결측치 대체  → fillna() 함수로 특정 값(평균, 중앙값, 고정값 등)으로 채움

In [ ]:
# 실습을 위해 df에 결측치 추가
# np.nan : numpy에서 제공하는 NaN 값 → 특정 컬럼 전체를 결측치로 설정할 때 사용
import numpy as np

df['학급'] = np.nan  # '학급' 컬럼 전체를 NaN으로 변경
df

In [ ]:
# ─────────────────────────────────────────────
# fillna() : 결측치를 특정 데이터로 채우기
# ─────────────────────────────────────────────
# - fillna(값) : NaN 데이터를 지정한 값으로 채운 결과를 리턴
# - 원본 데이터(df1)는 변경되지 않음 → 결과를 변수에 저장해야 반영됨

df1 = df.copy()  # 원본 보존을 위해 복사본 생성

result_df = df1.fillna('임시데이터')  # 모든 NaN을 '임시데이터' 문자열로 채움
result_df  # 결측치가 채워진 데이터프레임 확인

# df1은 변경되지 않았음을 확인
df1

In [ ]:
# 특정 컬럼의 결측치만 채우기
# df['컬럼명'].fillna(값) → 해당 컬럼의 NaN만 지정 값으로 채움

df1 = df.copy()

# '취미' 컬럼의 결측치만 '없음'으로 채우기
df1['취미'].fillna('없음')

In [4]:
data = {
    '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
             '2024006', '2024007', '2024008', '2024009', '2024010'],
    '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
             '강하은', '윤도현', '임지유', '한준서', '오서현'],
    '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', None, '정보통신',
             '컴퓨터공학', None, '정보통신', '컴퓨터공학', '소프트웨어'],
    '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
    '파이썬점수': [85, 92, None, 95, 88, 73, 90, None, 76, 94],
    '자바점수': [90, None, 82, 88, 92, None, 95, 78, 80, 87],
    '출석률': [95.0, 98.0, 85.0, None, 90.0, 78.0, None, 88.0, 82.0, 96.0]
}

df = pd.DataFrame(data)
df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1   85.0  90.0  95.0
1  2024002  이서연   정보통신   2   92.0   NaN  98.0
2  2024003  박지호  컴퓨터공학   1    NaN  82.0  85.0
3  2024004  최수아    NaN   3   95.0  88.0   NaN
4  2024005  정우진   정보통신   2   88.0  92.0  90.0
5  2024006  강하은  컴퓨터공학   1   73.0   NaN  78.0
6  2024007  윤도현    NaN   3   90.0  95.0   NaN
7  2024008  임지유   정보통신   2    NaN  78.0  88.0
8  2024009  한준서  컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현  소프트웨어   3   94.0  87.0  96.0

In [ ]:
# ─────────────────────────────────────────────
# 결측치 확인 방법
# ─────────────────────────────────────────────
# isnull()     : 각 데이터가 결측치면 True, 아니면 False로 표현
# isnull().any(axis=1) : 행 기준으로 하나라도 결측치가 있으면 True
# isnull().sum()       : 컬럼별 결측치 개수 합계

df.isnull()  # 전체 결측치 여부 표

# 결측치가 있는 행만 필터링 (axis=1 → 열 방향으로 any 검사 → 행 단위 결과)
df[df.isnull().any(axis=1)]

# 각 컬럼별 결측치 개수 확인
df.isnull().sum()

In [23]:
#df의 내용을 test_df로 복사(df의 내용은 기존 내용 보존을 위해)
test_df = df.copy()
test_df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1   85.0  90.0  95.0
1  2024002  이서연   정보통신   2   92.0   NaN  98.0
2  2024003  박지호  컴퓨터공학   1    NaN  82.0  85.0
3  2024004  최수아    NaN   3   95.0  88.0   NaN
4  2024005  정우진   정보통신   2   88.0  92.0  90.0
5  2024006  강하은  컴퓨터공학   1   73.0   NaN  78.0
6  2024007  윤도현    NaN   3   90.0  95.0   NaN
7  2024008  임지유   정보통신   2    NaN  78.0  88.0
8  2024009  한준서  컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현  소프트웨어   3   94.0  87.0  96.0

In [ ]:
# ─────────────────────────────────────────────
# dropna() : 결측치 제거
# ─────────────────────────────────────────────
# 주요 매개변수:
#   axis = 'index'   (기본값) → 결측치가 있는 행을 삭제
#   axis = 'columns'          → 결측치가 있는 열을 삭제
#   how  = 'any'     (기본값) → 결측치가 하나라도 존재하면 삭제
#   how  = 'all'              → 모든 데이터가 결측치일 때만 삭제
#   subset = ['컬럼명']        → 특정 컬럼에 결측치가 있는 행만 제거
#
# ※ dropna()는 결측치가 제거된 새로운 DataFrame을 리턴, 원본은 유지

# 결측치가 있는 행 모두 제거 (기본: axis='index', how='any')
result1_df = test_df.dropna()
result1_df

# 원본 데이터 유지 확인
test_df

# 결측치가 하나라도 있는 열(컬럼) 제거
result2_df = test_df.dropna(axis='columns', how='any')
result2_df

# '파이썬점수' 컬럼에 결측치가 있는 행만 제거
result3_df = test_df.dropna(subset=['파이썬점수'])
result3_df

# '파이썬점수', '자바점수' 둘 다 결측치가 있는 행 제거 (두 컬럼 중 하나라도 NaN이면 제거)
result4_df = test_df.dropna(subset=['파이썬점수', '자바점수'])
result4_df

In [ ]:
# ─────────────────────────────────────────────
# fillna() : 결측치를 통계값으로 대체
# ─────────────────────────────────────────────
# 결측치를 고정 문자열 대신 해당 컬럼의 통계값으로 채우는 방식
# 주로 사용하는 통계값:
#   mean()   → 평균  (이상치에 민감)
#   median() → 중앙값 (이상치에 강건)
#   max()    → 최댓값
#   min()    → 최솟값

test_df['파이썬점수'].mean()    # 평균
test_df['파이썬점수'].max()     # 최댓값
test_df['파이썬점수'].min()     # 최솟값
test_df['파이썬점수'].median()  # 중앙값

# '파이썬점수' 컬럼의 결측치를 해당 컬럼 평균으로 채우기
# 원본 컬럼에 직접 재할당하여 df를 영구 변경
test_df['파이썬점수'] = test_df['파이썬점수'].fillna(test_df['파이썬점수'].mean())
test_df

In [ ]:

test_data = {
    '직원번호': ['E001', 'E002', 'E003', 'E004', 'E005',
               'E006', 'E007', 'E008', 'E009', 'E010',
               'E011', 'E012'],
    '이름': ['김태호', '이지은', '박현우', '최민서', '정다은',
             '강준혁', '윤소희', '임재원', '한지수', '오민준',
             '배수연', '신동욱'],
    '부서': ['개발', '마케팅', '개발', None, '인사',
             '개발', None, '마케팅', '인사', '개발',
             '마케팅', None],
    '직급': ['대리', '과장', '사원', '대리', '과장',
             None, '사원', '대리', None, '과장',
             '사원', '대리'],
    '연봉': [3800, 4500, 3200, None, 4200,
             3900, 3100, None, 4000, 4800,
             3300, None],
    '성과점수': [88, 92, None, 78, 95,
               None, 82, 90, 74, None,
               85, 91],
    '근속연수': [3, 7, 1, 4, 8,
               5, 2, None, 6, 9,
               None, 4]
}

In [69]:
#1. 위 test_data를 pandas의 DataFrame으로 만드세요
practice_df = pd.DataFrame(test_data)
practice_df

    직원번호   이름   부서   직급      연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.0  88.0   3.0
1   E002  이지은  마케팅   과장  4500.0  92.0   7.0
2   E003  박현우   개발   사원  3200.0   NaN   1.0
3   E004  최민서  NaN   대리     NaN  78.0   4.0
4   E005  정다은   인사   과장  4200.0  95.0   8.0
5   E006  강준혁   개발  NaN  3900.0   NaN   5.0
6   E007  윤소희  NaN   사원  3100.0  82.0   2.0
7   E008  임재원  마케팅   대리     NaN  90.0   NaN
8   E009  한지수   인사  NaN  4000.0  74.0   6.0
9   E010  오민준   개발   과장  4800.0   NaN   9.0
10  E011  배수연  마케팅   사원  3300.0  85.0   NaN
11  E012  신동욱  NaN   대리     NaN  91.0   4.0

In [ ]:
# 실습 2. 컬럼별 결측치 개수 파악
# isnull().sum() → 각 컬럼에 몇 개의 결측치가 있는지 확인

practice_df.isnull().sum()

In [ ]:
# 실습 3. 결측치가 있는 행만 출력
# isnull().any(axis=1) : 행 기준으로 결측치가 하나라도 있으면 True → 해당 행만 필터링

practice_df[practice_df.isnull().any(axis=1)]

In [ ]:
# 실습 4. 결측치가 하나라도 있는 행을 모두 제거하고, 제거된 행 수 출력
# ※ 버그 수정: len(practice_df) - len(practice_df) 는 항상 0
#              올바른 계산: 전체 행 수 - dropna() 후 행 수

practice_df.dropna()  # 결측치 포함 행 모두 제거한 결과 확인

# 제거된 행 수 계산
removed_count = len(practice_df) - len(practice_df.dropna())
print(f'제거된 행 수: {removed_count}개')

In [ ]:
#5. 원본데이터에서 연봉과 성과점수 중 결측치가 포함된 행을 제거
result = practice_df.dropna(subset=['연봉', '성과점수'])
result

    직원번호   이름   부서   직급      연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.0  88.0   3.0
1   E002  이지은  마케팅   과장  4500.0  92.0   7.0
4   E005  정다은   인사   과장  4200.0  95.0   8.0
6   E007  윤소희  NaN   사원  3100.0  82.0   2.0
8   E009  한지수   인사  NaN  4000.0  74.0   6.0
10  E011  배수연  마케팅   사원  3300.0  85.0   NaN

In [75]:
#6. 아래 요구사항에 맞게 결측치를 채우세요
#1) 부서의 결측치는 '미배정'으러 채움
#2) 연봉의 결측치는 연봉 평균으로 채움
#3) 성과점수 결측치는 중앙값으로 채움

practice_df['부서'] = practice_df['부서'].fillna('미배정')
practice_df['연봉'] = practice_df['연봉'].fillna(practice_df['연봉'].mean())
practice_df['성과점수'] = practice_df['성과점수'].fillna(practice_df['성과점수'].median())
practice_df

    직원번호   이름   부서   직급           연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.000000  88.0   3.0
1   E002  이지은  마케팅   과장  4500.000000  92.0   7.0
2   E003  박현우   개발   사원  3200.000000  88.0   1.0
3   E004  최민서  미배정   대리  3866.666667  78.0   4.0
4   E005  정다은   인사   과장  4200.000000  95.0   8.0
5   E006  강준혁   개발  NaN  3900.000000  88.0   5.0
6   E007  윤소희  미배정   사원  3100.000000  82.0   2.0
7   E008  임재원  마케팅   대리  3866.666667  90.0   NaN
8   E009  한지수   인사  NaN  4000.000000  74.0   6.0
9   E010  오민준   개발   과장  4800.000000  88.0   9.0
10  E011  배수연  마케팅   사원  3300.000000  85.0   NaN
11  E012  신동욱  미배정   대리  3866.666667  91.0   4.0

In [76]:
#7. 결측치가 모두 처리된 데이터에서 성과점수가 90점 이상인 직원의 이름, 부서, 성과점수를 조회

practice_df[practice_df['성과점수'] >= 90][['이름', '부서', '성과점수']]

     이름   부서  성과점수
1   이지은  마케팅  92.0
4   정다은   인사  95.0
7   임재원  마케팅  90.0
11  신동욱  미배정  91.0