In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('test2.xlsx')
df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반    90    70  80   독서
1  이자바  자바반    80    80  80  NaN
2  박자바  자바반    70    80  75  NaN
3  최캐드  캐드반   100    70  85   요가
4  정캐드  캐드반    90    90  90   축구

In [ ]:
#결측치 : 데이터 세트에서 누락된 값(비어있는 데이터, NaN 데이터)
#결측치 제거 : 비어있거나 NaN 데이터를 삭제 => 비어있거나 NaN 데이터를 특정 데이터로 채워줌

In [7]:
#실습을 위해 df에 결측치를 추가
import numpy as np

df['학급'] = np.nan
df

    이름  학급  국어점수  영어점수  평균   취미  학습
0  김자바 NaN    90    70  80   독서 NaN
1  이자바 NaN    80    80  80  NaN NaN
2  박자바 NaN    70    80  75  NaN NaN
3  최캐드 NaN   100    70  85   요가 NaN
4  정캐드 NaN    90    90  90   축구 NaN

In [12]:
#결측치를 특정 데이터로 채우기

df1 = df.copy()

#fillna 함수는 nan 데이터에 특정 데이터를 채운 결과를 리턴해줌 (원본 데이터는 변경사항 없음)
result_df = df1.fillna('임시데이터')

#결측치가 채워진 데이터프레임
result_df

df1

    이름  학급  국어점수  영어점수  평균   취미  학습
0  김자바 NaN    90    70  80   독서 NaN
1  이자바 NaN    80    80  80  NaN NaN
2  박자바 NaN    70    80  75  NaN NaN
3  최캐드 NaN   100    70  85   요가 NaN
4  정캐드 NaN    90    90  90   축구 NaN

In [16]:
#특정 컬럼의 결측치 제거
df1 = df.copy()

#취미 컬럼의 결측치만 특정 데이터로 채우기
df1['취미'].fillna('없음')

0    독서
1    없음
2    없음
3    요가
4    축구
Name: 취미, dtype: str